[package]
name = "day5"
version = "0.1.0"
authors = ["2ndTaleStudio <43264484+2ndTaleStudio@users.noreply.github.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]